image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
- build
- deploy

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-master:
  stage: deploy
  script:
  - docker pull $CI_REGISTRY_IMAGE
  - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
  - docker tag $CI_REGISTRY_IMAGE registry.heroku.com/rest-tunes/web
  - docker push registry.heroku.com/rest-tunes/web
  - docker run --rm -e HEROKU_API_KEY=$HEROKU_TOKEN wingrunr21/alpine-heroku-cli container:release web --app rest-tunes
  only:
    - master